config/routes.rb
Rails.application.routes.draw do

  resources :accounts, :except => :show do
    resources :charges, :except => [:edit, :update, :destroy] do
      member do
        post "processed"
        post "failed"
      end
    end
  end

  get "dashboards/charges" => "dashboards#charges"

  root "accounts#index"

end

app/models/account.rb
class Account < ActiveRecord::Base
  has_many :charges
end

app/models/charge.rb
class Charge < ActiveRecord::Base
  belongs_to :account
  has_many :charge_states

  default_scope { order("created_at asc") }

  scope :all_for_account, ->(account) { where(:account => account) }

  scope :find_for_account, ->(account, charge_id) {
    all_for_account(account).find(charge_id)
  }

  scope :all_in_progress, -> {
    where <<-eos
      id in
        (select cs1.charge_id from charge_states as cs1
         left join charge_states as cs2
         on (cs1.charge_id = cs2.charge_id and cs1.created_at < cs2.created_at)
         where cs2.id is null and cs1.state not in (#{ChargeState.final_states.join(",")}))
    eos
  }

  scope :all_finalized, -> {
    where <<-eos
      id in
        (select cs1.charge_id from charge_states as cs1
         left join charge_states as cs2
         on (cs1.charge_id = cs2.charge_id and cs1.created_at < cs2.created_at)
         where cs2.id is null and cs1.state in (#{ChargeState.final_states.join(",")}))
    eos
  }

  scope :all_with_state, ->(state) {
    where <<-eos
      id in
        (select cs1.charge_id from charge_states as cs1
         left join charge_states as cs2
         on (cs1.charge_id = cs2.charge_id and cs1.created_at < cs2.created_at)
         where cs2.id is null and cs1.state = #{ChargeState.states[state]})
    eos
  }

  before_create :processing!

  def readonly?
    persisted?
  end

  def states
    charge_states
  end

  def state
    states.last
  end

  def processing!
    states.build(:state => ChargeState.states[:processing], :created_at => created_at)
  end

  def processed!
    states.create(:state => ChargeState.states[:processed])
  end

  def failed!
    states.create(:state => ChargeState.states[:failed])
  end
end

app/models/charge_state.rb
class ChargeState < ActiveRecord::Base
  belongs_to :charge

  default_scope { order("created_at ASC") }

  enum :state => {
    :processing => 0,
    :processed  => 1,
    :failed     => 2
  }

  def readonly?
    persisted?
  end

  def self.final_states
    [
      states[:processed],
      states[:failed]
    ]
  end

  def in_progress?
    !finalized?
  end

  def finalized?
    self.class.final_states.include?(read_attribute(:state))
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to account_charges_path(@account), notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to account_charges_path(@account), notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :set_account
  before_action :set_charge, :only => [:show, :processed, :failed]

  # GET /charges
  # GET /charges.json
  def index
    @charges = Charge.all_for_account(@account)
  end

  # GET /charges/1
  # GET /charges/1.json
  def show
  end

  # GET /charges/new
  def new
    @charge = Charge.new
  end

  # POST /charges
  # POST /charges.json
  def create
    @charge = Charge.new do |record|
      record.amount_in_cents = params[:charge][:amount_in_cents]
      record.account_id = @account.id
    end

    respond_to do |format|
      if @charge.save
        format.html { redirect_to account_charge_path(@account, @charge), notice: 'Charge was successfully created.' }
        format.json { render :show, status: :created, location: @charge }
      else
        format.html { render :new }
        format.json { render json: @charge.errors, status: :unprocessable_entity }
      end
    end
  end

  def processed
    @charge.processed!

    respond_to do |format|
      format.html { redirect_to account_charge_path(@account, @charge), notice: 'Charge was successfully processed.' }
      format.json { render :show, status: :ok, location: @charge }
    end
  end

  def failed
    @charge.failed!

    respond_to do |format|
      format.html { redirect_to account_charge_path(@account, @charge), notice: 'Charge failed :(' }
      format.json { render :show, status: :internal_server_error, location: @charge }
    end
  end

private
  def set_charge
    @charge = Charge.find_for_account(@account, params[:id])
  end

  def set_account
    @account = Account.find(params[:account_id])
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def charges
    @processing = Charge.all_with_state(:processing).count
    @processed  = Charge.all_with_state(:processed).count
    @failed     = Charge.all_with_state(:failed).count
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<h1>Listing accounts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= link_to account.name, account_charges_path(account) %></td>
        <!-- <td><%= link_to 'Edit', edit_account_path(account) %></td> -->
        <!-- <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/charges/_form.html.erb
<%= form_for([@account, @charge]) do |f| %>
  <% if @charge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@charge.errors.count, "error") %> prohibited this charge from being saved:</h2>

      <ul>
      <% @charge.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :amount_in_cents %><br>
    <%= f.number_field :amount_in_cents %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/charges/index.html.erb
<h1>Listing charges for <%= @account.name %></h1>

<table>
  <thead>
    <tr>
      <th>Amount in cents</th>
      <th>Last Updated At</th>
      <th>Current state</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @charges.each do |charge| %>
      <tr>
        <td><%= charge.amount_in_cents %></td>
        <td><%= charge.state.created_at %></td>
        <td><%= charge.state.state %></td>
        <td><%= link_to 'Show', account_charge_path(@account, charge) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Charge', new_account_charge_path(@account) %> |
<%= link_to "Edit account", edit_account_path(@account) %>

app/views/charges/new.html.erb
<h1>New charge</h1>

<%= render 'form' %>

<%= link_to 'Back', account_charges_path(@account) %>

app/views/charges/show.html.erb
<h1>Charge #<%= @charge.id %></h1>

<p id="notice"><%= notice %></p>

<p>
  <strong>Amount in cents:</strong>
  <%= @charge.amount_in_cents %>
</p>

<p>
  <strong>Account:</strong>
  <%= link_to @charge.account.name, account_charges_path(@account) %>
</p>

<p>
  <strong>Last Updated At:</strong>
  <%= @charge.created_at %>
</p>

<p>
  <strong>Current state:</strong>
  <%= @charge.state.state %>
  <% if @charge.state.in_progress? %>
    <br>
    <%= link_to "Mark processed", processed_account_charge_path(@account, @charge), :method => :post %> |
    <%= link_to "Mark failed", failed_account_charge_path(@account, @charge), :method => :post %>
  <% end %>
</p>


<%= link_to 'Back to account charges', account_charges_path(@account) %>

app/views/dashboards/charges.html.erb
<h1>Charges Dashboard</h1>

<ul>
  <li>Processing: <%= @processing %></li>
  <li>Processed: <%= @processed %></li>
  <li>Failed: <%= @failed %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ImmutableExample</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div><%= link_to "Accounts", accounts_path %> | <%= link_to "Charges Dashboard", dashboards_charges_path %></div>

<%= yield %>

</body>
</html>